[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zumi-ai"
version = "0.1.23"
authors = [
  { name="dr", email="drlee@robolink.co.kr" },
]
description = "Zumi AI for library."
readme = "README.md"
requires-python = ">=3.9" #pro is 3.12
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["ai", "zumi", "robotics"]

# 초보자를 위한 최소 필수 의존성 (pip install zumi-ai 시 설치)
# [project.dependencies] 바로 아래에 배열 형태로 나열해야 합니다.
dependencies = [
  "colorama==0.4.6",
  "pynput==1.8.1",
  "pyserial==3.5",
]

# 파워 유저를 위한 추가/선택적 의존성 (pip install zumi-ai[pro] 시 설치)
[project.optional-dependencies]
pro = [
  "mediapipe==0.10.21",
  "numpy==1.26.4",
  "opencv-contrib-python==4.6.0.66",
  "pupil-apriltags==1.0.4.post11",
  "tensorflow==2.19.0",
  "ultralytics==8.3.100",
  "websocket-client==1.8.0",
]


[project.urls]
"Homepage" = "https://github.com/truedo/zumi_mini_python_backup"
"Bug Tracker" = "https://github.com/truedo/zumi_mini_python_backup/issues"

[tool.setuptools]
packages = ["zumi_AI"]
include-package-data = true

[tool.setuptools.package-data]
"zumi_AI" = ["res/model/*.tflite"]