name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 이 워크플로우 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 여기가 중요합니다! HTML 파일이 있는 경로를 정확히 지정해줍니다.
          publish_dir: ./Zumi_AI/docs/build/html