name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 이 워크플로우 실행

permissions: # 이 부분을 추가해야 합니다.
  contents: write # 저장소 콘텐츠에 대한 쓰기 권한 부여
  pages: write # GitHub Pages 배포를 위한 쓰기 권한 부여 (필수)
  id-token: write # OpenID Connect (OIDC) 사용을 위한 권한 (필요 시)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Zumi_AI/docs/build/html